#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "scrapy" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d66d6e76009b12447604196875a463b61d10721140032a8084a0a52df7f4788f

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - scrapy = scrapy.cmdline:execute

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - twisted >=21.7.0
    - cryptography >=37.0.0
    - cssselect >=0.9.1
    - itemloaders >=1.0.1
    - parsel >=1.5.0
    - pyopenssl >=22.0.0
    - queuelib >=1.4.2
    - service_identity >=18.1.0
    - w3lib >=1.17.0
    - zope.interface >=5.1.0
    - protego >=0.1.15
    - itemadapter >=0.1.0
    - setuptools
    - packaging
    - tldextract
    - lxml >=4.6.0
    - pydispatcher >=2.0.5
    - defusedxml >=0.7.1

test:
  source_files:
    - conftest.py
    - pytest.ini
    - tests
  imports:
    - scrapy
  requires:
    - pip
    # Tests requirements
    - attrs
    - pytest
    - pytest-cov
    - pytest-xdist
    - testfixtures
    - uvloop # [not win]
    - ipython
    - pexpect  # [win]
  commands:
    - pip check
    - scrapy version -v
    - scrapy bench
    - scrapy --help
    # win-64: FTP tests: connection refused on 127.0.0.1
    # win-64: test_shutdown_forced
    # linux-s390x: test_utf16 fails due to endianness
    # test_start_requests_laziness sporadic failures
    # test_mediatype_parameters fails due to regex issue in parse_data_uri
    # Https10TestCase, Http11ProxyTestCase, EngineTest, BytesReceivedEngineTest, WebClientSSLTestCase see: https://github.com/scrapy/scrapy/issues/5961
    - set "PYTHONIOENCODING=utf8"  # [win]
    - pytest -n auto -k "not (FTPTestCase or FTPFeedStorageTest or TestFTPFileStore or test_utf16 or test_start_requests_laziness or test_mediatype_parameters or Https10TestCase or Http11ProxyTestCase or EngineTest or test_shutdown_forced or BytesReceivedEngineTest or WebClientSSLTestCase or test_delay)"

about:
  home: https://scrapy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - redapple
