#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a68ed41f7173679f160c4cef2db05288548c21e7164170552adae8b13cefaab

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - scrapy = scrapy.cmdline:execute
  number: 0

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.6
    - setuptools
    - pywin32  # [win]

    # Same order as setup.py:
    - twisted >=17.9.0
    - cryptography >=2.0
    - cssselect >=0.9.1
    - itemloaders >=1.0.1
    - lxml >=3.5.0
    - parsel >=1.5.0
    - pydispatcher >=2.0.5
    - pyOpenSSL >=16.2.0
    - queuelib >=1.4.2
    - service_identity >=16.0.0
    - w3lib >=1.17.0
    - zope.interface >=4.1.3
    - protego >=0.1.15
    - itemadapter >=0.1.0
    # deps of twisted[http2]
    - h2 >=3.0, <4.0
    - priority >=1.1.0, <2.0

test:
  imports:
    - scrapy

  commands:
    # Ideally, we will run tests here but we require to provide the tests
    # requirements first.
    - scrapy bench

about:
  home: https://scrapy.org/
  license: BSD-3-Clauses
  license_family: BSD
  license_file: LICENSE
  summary: A high-level Web Crawling and Web Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - redapple
