#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68c48f01a58636bdf0f6fcd5035a19ecf277b58af24bd70c36dc6e556df3e005

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - scrapy = scrapy.cmdline:execute
  number: 0

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - twisted >=13.1.0  # [not win]
    - twisted >=16.4.0  # [win]
    - w3lib >=1.17.0
    - queuelib
    - itemadapter
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - parsel >=1.5
    - pydispatcher >=2.0.5
    - service_identity

test:
  imports:
    - scrapy

  commands:
    # Ideally, we will run tests here but we require to provide the tests
    # requirements first.
    - scrapy bench

about:
  home: https://scrapy.org/
  license: BSD 3-Clauses
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - redapple
