travis:
  secure:
    BINSTAR_TOKEN: FJScvZzxeBvGtY79VCPWZYDNyOh+jBBNmGTr4d3SmUN5qlgsEVNDcxUzFJILtguyPXZYLV1Lyw1QPQFPFbFD9DsXPzUYuXJ6wg97syVGynNdrpEsLh8WHCSdhuQ47XPVOYFAluwWp/h1ISlXFxxe876ePn6ESo3lxjXRu1NpMG9HoXEyKGBplMK3JqfR+m0mFaZju5N9Eg0Ezoqj1W4q3juYffvMr8RsUOzdA56XgDdqdQSwncjeXN3JZRfuQfVRVUD643MU6kSOPfIiDNRbAVAj20WE8QbDjRePrt7WW6NzJ/DY0vNyFo+ZzBUvo5Wv9DTtp6C40D19TQ138Eod0R3UhuJ7AIt2H2B/ZDvDvkvMW/kLtt5bSLPluGRb+wNLf5s7tLvaRzt75sl/JAWElTjNxcFhfzyhSfx5SvqRy3JLBdJe2+9tVAf7jvJsNp9fm22a+Wc5S4c78U4ZTIESaSVbP1+ntYHQyGnpf7hU5qI/j4tI8VJxwCx9lZzPl25bZ75l2v4TNWg4v54f6Ams7vkpZSPaAaOyQ9hzjMq7diAj//P/10sdmxd4LyNfiVwUll7lZ2g1XJJrxdFsEOl1QlKpeQZ624w33KUlgnfp3o0tbexDov2zcdz/3jnYBdQGaPdxItzxq00zBPOrs2psamVM829zI+TA8B6x4/d3Zic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
